config/routes.rb
Rails.application.routes.draw do  
  
  root "minions#index"
	get 'home/index'
  resources :minions do 
  	resources :reservations	
  end
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'myreservations' => "reservations#myreservations", as: "myreservations"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/minion.rb
class Minion < ApplicationRecord
	has_one_attached :image
	validates_presence_of :name, :description
	has_many :reservations, dependent: :destroy
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :minion
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates_presence_of :name
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reservations, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :store_location

def store_location
  # store last url as long as it isn't a /users path
  session[:previous_url] = request.fullpath unless request.fullpath =~ /\/users/
end

	def after_sign_up_path_for(resource)
	  session[:previous_url] || root_path
	end
	def after_sign_in_path_for(resource)
	  session[:previous_url] || root_path
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/minions_controller.rb
class MinionsController < ApplicationController
  before_action :set_minion, only: [:show, :edit, :update, :destroy]
  before_action :check_user, only: [:new, :edit, :update, :destroy]

  # GET /minions
  # GET /minions.json
  def index
    @minions = Minion.all
  end

  # GET /minions/1
  # GET /minions/1.json
  def show
  end

  # GET /minions/new
  def new
    @minion = Minion.new
  end

  # GET /minions/1/edit
  def edit
  end

  # POST /minions
  # POST /minions.json
  def create
    @minion = Minion.new(minion_params)   

    respond_to do |format|
      if @minion.save
        format.html { redirect_to @minion, notice: t('.new_success') }
        format.json { render :show, status: :created, location: @minion }
      else
        format.html { render :new }
        format.json { render json: @minion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /minions/1
  # PATCH/PUT /minions/1.json
  def update
    respond_to do |format|
      if @minion.update(minion_params)
        format.html { redirect_to @minion, notice: t('.edit_success') }
        format.json { render :show, status: :ok, location: @minion }
      else
        format.html { render :edit }
        format.json { render json: @minion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /minions/1
  # DELETE /minions/1.json
  def destroy
    @minion.destroy
    respond_to do |format|
      format.html { redirect_to minions_url, notice: t('.destroy_success') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_minion
      @minion = Minion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def minion_params
      params.require(:minion).permit(:name, :description, :image)
    end
    def check_user
      if current_user.nil?
        redirect_to root_path, notice: t('gru_only')
      else
        if !current_user.is_admin
          redirect_to root_path, notice: t('gru_only')
        end
      end
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	
	#POST/resource Create a new user and sign up 
	def create
		build_resource(sign_up_params)
		resource.save
		if resource.persisted?
			if resource.active_for_authentication?
				if(resource.email == "bruno@krotedev.com.br" || resource.email == "raquel@inventosdigitais.com.br")
					resource.update(is_admin: true)
				end
				set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
	end
	
	

	private

	def sign_up_params
		params.require(:user).permit(:name, :phone, :email ,:password, :password_confirmation)
	end

	def account_update_params
		params.require(:user).permit(:name, :phone, :email ,:password, :password_confirmation, :current_password)
	end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_minion, except:[:myreservations]
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]  
  before_action :authenticate_user!

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = current_user.reservations.all
  end
  def myreservations
    @reservations = current_user.reservations.all
  end
  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    # @reservation = @minion.reservations.new
    @reservation = current_user.reservations.build
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create    
    @reservation = @minion.reservations.new(reservation_params)
    @reservation.user = current_user    
    respond_to do |format|
      if @reservation.save
        ReservationMailer.new_reservation_user(@reservation).deliver
        ReservationMailer.new_reservation_admin(@reservation).deliver
        format.html { redirect_to root_path, notice: t('reservations.reservation_success') }
        format.json { render :show, status: :created, location: root_path }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # get the minion id
    def set_minion
      @minion = Minion.find(params[:minion_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = @minion.reservations.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:minion_id, :user_id, :message)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/minions_helper.rb
module MinionsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/home/_footer.html.haml
%footer.main-footer.container-fluid
	.row
		.container
			.row
				.col-12.col-md-3
					%h2=t('nav.contact')
					%ul
						%li
							%i.fa.fa-envelope-o{:"aria-hidden" => "true"}
							=link_to t('nav.mail'), "#"
						%li
							%i.fa.fa-phone{:"aria-hidden" => "true"}
							=link_to t('nav.phone'), "#"
				.col-12.col-md-3
					%h2=t('nav.institutional')
					%ul
						%li=t('nav.about')
				.col-12.col-md-3
					%h2=t('nav.links')
					%ul
						%li=link_to t('nav.contact_page'), "#"
						%li=link_to t('nav.reservations'), "#"
						%li=link_to t('nav.faq'), "#"
						%li=link_to t('nav.privacy')
				.col-12.col-md-3
					%h2=t('nav.social')
					%ul
						%li
							%i.fa.fa-facebook-square{:"aria-hidden" => "true"}
							=link_to t('nav.facebook'), "#"
						%li
							%i.fa.fa-twitter-square{:"aria-hidden" => "true"}
							=link_to t('nav.twitter'), "#"
						%li
							%i.fa.fa-pinterest-square{:"aria-hidden" => "true"}
							=link_to t('nav.pinterest'), "#"
						%li
							%i.fa.fa-instagram{:"aria-hidden" => "true"}
							=link_to t('nav.instagram'), "#"

app/views/home/_header.html.haml
%header.main-header
  .container
    %nav.navbar.navbar-expand-lg.navbar-light.main-nav      
      %a.navbar-brand{href: root_path}
        =image_tag('/assets/minion_store_logo')
        %h1
          %b Minions
          Store
      %button{class: "navbar-toggler", type: "button", 'data-toggle': "collapse", 'data-target': "#mainMenu", 'aria-controls': "mainMenu", 'aria-expanded': "false", 'aria-label': "Toggle Navigation"}
        %span.navbar-toggler-icon
      .collapse.navbar-collapse#mainMenu
        %ul.navbar-nav.ml-auto
          - if user_signed_in?
            -if current_user.is_admin?
              %li.nav-item.dropdown
                %a#navbarMinionDropdown.nav-link.dropdown-toggle{:role => "button", :"data-toggle" => "dropdown", :"aria-haspopup" => "true", :"aria-expanded" => "false"}
                  =t('nav.minions')
                .dropdown-menu{:"aria-labelledy" => "navbarMinionDropdown"}
                  =link_to t('nav.minions'), minions_path, class: 'dropdown-item'
                  =link_to t('nav.new_minion'), new_minion_path, class: 'dropdown-item'
            %li.nav-item
              =link_to t('nav.myreservations'), myreservations_path, class: 'nav-link'
            %li.nav-item
              %a{:href => edit_user_registration_path, class: 'nav-link'}
                =current_user.name
                -if current_user.is_admin?
                  %small=t("nav.admin")            
            %li.nav-item
              =link_to t('nav.log_out'), destroy_user_session_path, method: :delete, class: 'nav-link'            
            
          -else            
            %li.nav-item
              =link_to t('nav.sign_in'), new_user_session_path, class: 'nav-link'
            %li.nav-item
              =link_to t('nav.sign_up'), new_user_registration_path, class: 'nav-link'

app/views/home/index.html.haml
%h1=t('home.welcome')

app/views/layouts/application.html.haml
!!!
%html
	%head
		%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
		%title Minions Store
		= csrf_meta_tags
		= csp_meta_tag
		=favicon_link_tag  "/assets/favicon/favicon" , rel: "shortcut icon" 
		=favicon_link_tag  "/assets/favicon/apple-icon-57x57.png" , rel: "apple-touch-icon" , sizes: "57x57" 
		=favicon_link_tag  "/assets/favicon/apple-icon-60x60.png" , rel: "apple-touch-icon" , sizes: "60x60" 
		=favicon_link_tag  "/assets/favicon/apple-icon-72x72.png" , rel: "apple-touch-icon" , sizes: "72x72" 
		=favicon_link_tag  "/assets/favicon/apple-icon-76x76.png" , rel: "apple-touch-icon" , sizes: "76x76" 
		=favicon_link_tag  "/assets/favicon/apple-icon-114x114.png" , rel: "apple-touch-icon" , sizes: "114x114" 
		=favicon_link_tag  "/assets/favicon/apple-icon-120x120.png" , rel: "apple-touch-icon" , sizes: "120x120" 
		=favicon_link_tag  "/assets/favicon/apple-icon-144x144.png" , rel: "apple-touch-icon" , sizes: "144x144" 
		=favicon_link_tag  "/assets/favicon/apple-icon-152x152.png" , rel: "apple-touch-icon" , sizes: "152x152" 
		=favicon_link_tag  "/assets/favicon/apple-icon-180x180.png" , rel: "apple-touch-icon" , sizes: "180x180" 
		=favicon_link_tag  "/assets/favicon/android-icon-192x192.png" , rel: "icon" , type: "image/png" , sizes: "192x192"  
		=favicon_link_tag  "/assets/favicon/favicon-32x32.png" , rel: "icon" , type: "image/png" , sizes: "32x32" 
		=favicon_link_tag  "/assets/favicon/favicon-96x96.png" , rel: "icon" , type: "image/png" , sizes: "96x96" 
		=favicon_link_tag  "/assets/favicon/favicon-16x16.png" , rel: "icon" , type: "image/png" , sizes: "16x16" 
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
		= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
		%meta{:name=>"viewport", :content=> "width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=0"}/		
		%link{:type => "text/css", :rel => "stylesheet", :href => "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css"}
	%body{:class => "#{controller_name} #{action_name}"}
		=render('home/header')
		- if notice
			.notifications.notice
				%p=notice
		-if alert
			.notifications.alert
				%p=alert
		.main-content-wrapper
			= yield		
		=render('home/footer')

app/views/minions/_form.html.haml
= simple_form_for @minion do |f|  
  .form-group
    = f.input :name, input_html:{class: "form-control"}, label: t('.name')
  .form-group
    = f.input :description, input_html:{class: "form-control"}, label: t('.description')
  .form-group
    = f.input :image, input_html:{class: "form-control"}, label: t('.image')
  = f.button :submit, t(".create"), class: "btn btn-primary"

app/views/minions/edit.html.haml
.container
	.row.justify-content-center
		.col-12.col-md-6
			%header
				%h2=t('.edit')
			.minion-img
				-if @minion.image.attached?
					= image_tag @minion.image.variant(resize: "250x250")
			= render 'form'			
			= link_to t('.show'), @minion
			\|
			= link_to t('.back'), minions_path

app/views/minions/index.html.haml
%ul.minions-list.container
	.row
		-@minions.each do |minion|
			%li.minion-wrapper.col-12.col-md-3
				.content
					.img-wrapper
						-if minion.image.attached?
							= image_tag minion.image.variant(resize: "150x150")
					%h2=link_to minion.name, minion
					%p=truncate(minion.description, :length => 120)
					.reservation
						%a{href: new_minion_reservation_path(minion)}						
							=t('book_now')
							%i.fa.fa-heart{:"aria-hidden" => "true"}
					-if current_user
						-if current_user.is_admin
							.controls
								=link_to t('.edit'), edit_minion_path(minion)
								=link_to t('.destroy'), minion , method: :delete, data: { confirm: t('.are_you_sure') }

app/views/minions/new.html.haml
.container
	.row.justify-content-center
		.col-12.col-md-6
			%header
				%h2=t('.new')
			= render 'form'
			= link_to t('.back'), minions_path

app/views/minions/show.html.haml
.minion-wrapper.container
	.row		
		.col-12.col-md-4.img
			-if @minion.image.attached?				
				= image_tag @minion.image.variant(resize: "250x250")
		.col-12.col-md-7.info.ml-auto
			-if current_user
				-if current_user.is_admin
					.controls
						=link_to t('.edit'), edit_minion_path(@minion)
						=link_to t('.destroy'), @minion , method: :delete, data: { confirm: t('.are_you_sure') }
			%h2=@minion.name
			%p=@minion.description
			.reservation
				%a{href: new_minion_reservation_path(@minion)}
					=t('book_now')
					%i.fa.fa-heart{:"aria-hidden" => "true"}			

app/views/reservations/_form.html.haml
= simple_form_for [@minion, @reservation] do |f|  
  .form_group    
    = f.input :message, label: t('.message'), input_html:{class: "form-control"}
  .actions
    = f.button :submit, t(".reservate"), class: "btn btn-primary"

app/views/reservations/edit.html.haml
%h1 Editing reservation

= render 'form'

= link_to 'Show', @reservation
\|
= link_to 'Back', reservations_path

app/views/reservations/index.html.haml
%h1 Listing reservations

%table
  %thead
    %tr
      %th Minion
      %th User
      %th Message
      %th
      %th
      %th

  %tbody
    - @reservations.each do |reservation|
      %tr
        %td= reservation.minion
        %td= reservation.user
        %td= reservation.message
        %td= link_to 'Show', minion_reservation_path(@minion, reservation)
        %td= link_to 'Edit', edit_minion_reservation_path(@minion, reservation)
        -# %td= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Reservation', new_minion_reservation_path

app/views/reservations/myreservations.html.haml
.container.myreservations
	%header
		%h1=t('.myreservations')
	- if !@reservations.empty?		
		%ul.reservations-list.container
			.row
				- @reservations.each do |reservation|
					%li.col-12.col-md-3
						.content
							.img-wrapper
								-if reservation.minion.image.attached?
									=image_tag(reservation.minion.image.variant(resize: "150x150"))
							%h2								
								=link_to reservation.minion.name, minion_path(reservation.minion)
							%p
								%label=t('.created_at')								
								=l(reservation.created_at, format: :long)
	- else
		.empty_reservations
			%h2=t('.noreservations_html', user: current_user.name)
			=link_to t('.minions'), minions_path
	

app/views/reservations/new.html.haml
.container.reservation_new
	.row.justify-content-center
		.col-12.col-md-5.selected_minion
			.img_wrapper
				-if @minion.image.attached?				
					= image_tag @minion.image.variant(resize: "250x250")
			.info
				%h2=@minion.name
				%p=@minion.description
		.col-12.col-md-5
			%header
				%h3=t('.new_reservation')					
			= render 'form'
			= link_to t('.back'), minions_path

app/views/reservations/show.html.haml
%p#notice= notice

%p
  %b Minion:
  = @reservation.minion
%p
  %b User:
  = @reservation.user
%p
  %b Message:
  = @reservation.message

= link_to 'Edit', edit_reservation_path(@reservation)
\|
= link_to 'Back', reservations_path